language: go

matrix:
  fast_finish: true
  include:
  - go: 1.11.x
    env: GO111MODULE=on
  - go: 1.12.x
    env: GO111MODULE=on
  - go: 1.13.x
  - go: 1.14.x
  - go: 1.15.x

install:
  - go install golang.org/x/lint/golint

go_import_path: github.com/LiangXianSen/firewheel

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - make lint
  - make test